name: number-plates

services:
  ftp-server:
    container_name: ftp-server
    image: moujikov/number-plates-ftp
    restart: unless-stopped
    ports:
      - 21:21/tcp
      - 30001-30005:30001-30005/tcp
    volumes:
      - ./ftp/proftpd.conf:/etc/proftpd/proftpd.conf
      - ./ftp/entrypoint.sh:/entrypoint.sh
      - cameras:/home
      - logs_ftp-server:/var/log/proftpd
    env_file: ftp/.env
    environment:
      - PASSIVE_PORTS=30001-30005
      - FTP_USER_1=camera-1
      - FTP_PASSWORD_1=pass1
      - FTP_USER_2=camera-2
      - FTP_PASSWORD_2=pass2

  processor:
    container_name: processor
    image: moujikov/number-plates-processor
    restart: unless-stopped
    volumes:
      - ..:/app
      - cameras:/var/local/cameras
      - images:/var/local/images
    env_file: processor/.env
    environment:
      PYTHONDEVMODE: 1
      PYTHONASYNCIODEBUG: 1
      LOG_LEVEL: DEBUG
      # SYSTEM_LOG_LEVEL: DEBUG
      PROCESS_AT_ONCE: 3
    depends_on:
      database:
        condition: service_healthy
      scheduler:
        condition: service_healthy

  database:
    container_name: database
    image: postgres:18-alpine
    restart: unless-stopped
    env_file: database/.env
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - database:/var/lib/postgresql
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
      start_interval: 1s
    deploy:
      resources:
        limits:
          memory: 1G

  scheduler:
    container_name: scheduler
    image: moujikov/number-plates-scheduler
    restart: unless-stopped
    ports:
      - 8000:8000/tcp
    volumes:
      - ..:/app
    env_file: scheduler/.env
    environment:
      PYTHONDEVMODE: 1
      LOG_LEVEL: DEBUG
      # SYSTEM_LOG_LEVEL: DEBUG
      WORKER_URL_1: http://worker-1:8000
      WORKER_URL_2: http://worker-2:8000
    depends_on:
      worker-1:
        condition: service_healthy
      worker-2:
        condition: service_healthy

  worker-1:
    container_name: worker-1
    image: moujikov/number-plates-worker
    restart: unless-stopped
    volumes:
      - ..:/app
    env_file: worker/.env
    environment:
      PYTHONDEVMODE: 1
      LOG_LEVEL: DEBUG
      # SYSTEM_LOG_LEVEL: DEBUG

  worker-2:
    container_name: worker-2
    image: moujikov/number-plates-worker
    restart: unless-stopped
    volumes:
      - ..:/app
    env_file: worker/.env
    environment:
      PYTHONDEVMODE: 1
      LOG_LEVEL: DEBUG
      # SYSTEM_LOG_LEVEL: DEBUG

volumes:
  database:
  cameras:
  images:
  logs_ftp-server:
