CREATE USER processor WITH PASSWORD '__POSTGRES_PROCESSOR_PASSWORD__';
GRANT USAGE, CREATE ON SCHEMA public TO processor;
GRANT ALL PRIVILEGES ON DATABASE number_plates TO processor;

CREATE USER skud WITH PASSWORD '__POSTGRES_SKUD_PASSWORD__';
GRANT USAGE, CREATE ON SCHEMA public TO skud;
GRANT ALL PRIVILEGES ON DATABASE number_plates TO skud;

CREATE USER frontend WITH PASSWORD '__POSTGRES_FRONTEND_PASSWORD__';
GRANT USAGE, CREATE ON SCHEMA public TO frontend;
GRANT ALL PRIVILEGES ON DATABASE number_plates TO frontend;
