ServerName      "Cameras FTP Server"
ServerType      standalone
DefaultServer   on

# Umask 022 is a good standard umask to prevent new dirs and files
# from being group and world writable.
Umask           022

# To prevent DoS attacks, set the maximum number of child processes
# i.e. concurrent connections to 10.
MaxInstances    10

# Set the user and group under which the server will run.
User        nobody
Group       nogroup

# Do not check that user has valid shell, because we use /sbin/nologin for ftp users
RequireValidShell   off

# No wtmp in Alpine Linux default distribution
WtmpLog   off

# Better to disable IPv6 just in this case
UseIPv6   off

# Store files under temp name until fully uploaded
HiddenStores   on

# Do not allow files larger than 3 Mb
MaxStoreFileSize 3 Mb

# Allow access to upload directory only
DefaultRoot ~/upload

# Disable all but upload commands
<Limit ALL>
  DenyAll
</Limit>
<Limit CDUP CWD PWD XCWD XCUP>
  AllowAll
</Limit>
<Limit APPE STOR STOU>
  AllowAll
</Limit>

# Logging
LogOptions -Hostname +RoleBasedProcessLabels
TransferLog   /var/log/proftpd/transfer.log

# Extended logging – uncomment to debug issues with file uploads
# LogFormat     short "%h %u %{iso8601} \"%r\" %s %b"
# ExtendedLog   /var/log/proftpd/commands.log ALL short

# Include files generated from environment variables on startup
Include /etc/proftpd/conf.d/*.conf
